用户指南
------------

这部分文档很枯燥，以介绍 Flask 的背景开始，然后注重说明 Flask 的 Web 开发的各个步骤。

.. toctree::
   :maxdepth: 2

   foreword
   advanced_foreword
   installation
   quickstart
   tutorial/index
   templating
   testing
   errorhandling
   config
   signals
   views
   appcontext
   reqcontext
   blueprints
   extensions
   shell
   patterns/index
   deploying/index
   becomingbig

API 参考
-------------

如果你在寻找一个特定函数、类或方法的信息，那么这部分文档就是给你准备的。

.. toctree::
   :maxdepth: 2

   api

额外说明
----------------

这部分的设计说明，法律信息和变更记录为有兴趣的人准备。

.. toctree::
   :maxdepth: 2

   design
   htmlfaq
   security
   unicode
   extensiondev
   styleguide
   python3
   upgrading
   changelog
   license
   glossary
