用户指南
------------

这部分文档结构较为自由松散，从介绍 Flask 的背景开始，而后循序渐进地
介绍使用 Flask 进行 Web 开发的每个步骤。

.. toctree::
   :maxdepth: 2

   foreword
   advanced_foreword
   installation
   quickstart
   tutorial/index
   templating
   testing
   errorhandling
   config
   signals
   views
   appcontext
   reqcontext
   blueprints
   extensions
   shell
   patterns/index
   deploying/index
   becomingbig

API 参考
-------------

这部分文档用于查找具体函数、类或方法的说明信息。

.. toctree::
   :maxdepth: 2

   api

额外说明
----------------

设计说明，法律信息以及更新日志，为有兴趣的人而准备。

.. toctree::
   :maxdepth: 2

   design
   htmlfaq
   security
   unicode
   extensiondev
   styleguide
   python3
   upgrading
   changelog
   license
   glossary
